dist: bionic
language: php
php:
  - 7.3
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install
script:
  - vendor/bin/phpunit
